services:
  # ===================
  # ftp(file trancefar protcol)
  # ===================
  ftp:
    container_name: ftp
    build: ./services/ftp
    restart: always
    env_file: .env
    networks:
      - inception_net
    volumes:
      - wordpress_data:/var/www/html
      - static_site_data:/var/www/html/static-site
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
  # ===================
  # adminer 
  # ===================
  adminer:
    container_name: adminer
    build: ./services/adminer
    restart: always
    networks:
      - inception_net
    depends_on:
      - mariadb
  # ===================
  # MariaDB (Database)
  # ===================
  mariadb:
    container_name: mariadb
    build: ./services/marinadb
    restart: always
    env_file: .env
    networks:
      - inception_net
    volumes:
      - mariadb_data:/var/lib/mysql

  # ======================
  #   Redis Cache
  # ======================
  redis:
    container_name: redis
    build: ./services/redis
    restart: always
    
    networks:
      - inception_net

  # ======================
  #   WordPress + PHP-FPM
  # ======================
  wordpress:
    container_name: wordpress
    build: ./services/wordpress
    restart: always
    env_file: .env
    depends_on:
      - mariadb
      - redis
    networks:
      - inception_net
    volumes:
      - wordpress_data:/var/www/html

  # ======================
  #   NGINX
  # ======================
  nginx:
    container_name: nginx
    build: ./services/nginx
    restart: always
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      - wordpress_data:/var/www/html
# ======================
#   static-site
# ======================
  static-site:
    container_name: static-site
    build: ./services/static-site
    restart: always
    networks:
      - inception_net
    volumes:
      - static_site_data:/var/www/static
  upload-api:
    container_name: upload-api
    build: ./services/upload-api
    restart: always
    env_file: .env
    depends_on:
      - ftp
    networks:
      - inception_net
# ======================
#   Networks
# ======================
networks:
  inception_net:
    driver: bridge
    name: inception_net

# ======================
#   Volumes
# ======================
volumes:
  static_site_data:
    driver: local
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/wordpress
      o: bind
