version: '3.8'

services:
  # ===================
  # MariaDB (Database)
  # ===================
  mariadb:
    container_name: mariadb
    build: ./srcs/services/marinadb
    restart: always
    env_file: .env
    networks:
      - inception_net
    volumes:
      - mariadb_data:/var/lib/mysql

  # ======================
  #   Redis Cache
  # ======================
  redis:
    container_name: redis
    build: ./srcs/services/redis
    restart: always
    
    networks:
      - inception_net

  # ======================
  #   WordPress + PHP-FPM
  # ======================
  wordpress:
    container_name: wordpress
    build: ./srcs/services/wordpress
    restart: always
    env_file: .env
    depends_on:
      - mariadb
      - redis
    networks:
      - inception_net
    volumes:
      - wordpress_data:/var/www/html

  # ======================
  #   NGINX
  # ======================
  nginx:
    container_name: nginx
    build: ./srcs/services/nginx
    restart: always
    env_file: .env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      - wordpress_data:/var/www/html

# ======================
#   Networks
# ======================
networks:
  inception_net:
    driver: bridge
    name: inception_net

# ======================
#   Volumes
# ======================
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/mariadb
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${DATA_PATH}/wordpress
      o: bind