events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 443 ssl;
        server_name shattori.42.fr;

        ssl_certificate     /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;
        ssl_protocols       TLSv1.2 TLSv1.3;

        root  /var/www/html;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }
        
        location = /static/files {
            proxy_pass http://static-site:8080/files;
        }

        location /static/files/ {
            proxy_pass http://static-site:8080/files/;
            proxy_buffering off;
        }

        location = /static/upload {
            proxy_pass http://static-site:8080/upload;
            proxy_request_buffering off;
            client_max_body_size 20m;
        }

        location = /static {
            return 301 /static/;
        }

        location /static/ {
            proxy_pass http://static-site:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location = /health {
            access_log off;
            add_header Content-Type text/plain;
            return 20 "OK \n";
        }

        location ~ \.php$ {
            fastcgi_pass            wordpress:9000;
            fastcgi_index           index.php;
            fastcgi_param           SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include                 fastcgi_params;
        }
    }
}
