server {
    listen 8080;
    server_name _;
    root /var/www/static;
    index index.html;

    location /files/ {
        proxy_pass http://upload-api:8000/files/;
        proxy_buffering off;
    }

    location = /upload {
        proxy_pass http://upload-api:8000/upload;
        proxy_request_buffering off;
        client_max_body_size 20m;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
